config/routes.rb
Rails.application.routes.draw do
  root 'people#index'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  resources :maps, only: %i[show]
  resources :people, only: %i[index show]
  resources :users, only: %i[new create]
  get 'static_pages/top'
  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'
  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users
    resources :people
    resources :landmarks
  end
  resources :favorites, only: %i[create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :landmark

  validates :user_id, uniqueness: { scope: :landmark_id }
end

app/models/landmark.rb
class Landmark < ApplicationRecord
  validates :name, presence: true
  belongs_to :person
  
  has_many :favorites
end

app/models/person.rb
class Person < ApplicationRecord
    validates :name, presence: true
    has_many :landmarks, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true, length: { maximum: 225 }
  enum role: { general: 0, admin: 1 }

  has_many :favorites, dependent: :destroy
  has_many :landmarks, through: :favorites

  def favorite(landmark)
    landmarks << landmark
  end

  def unfavorite(landmark)
    landmarks.destroy(landmark)
  end

  def favorite?(landmark)
    landmarks.include?(landmark)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :success, :danger
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
      landmark = Landmark.find(params[:landmark_id])
      current_user.favorite(landmark)
      redirect_back fallback_location: people_path
    end
  
    def destroy
      landmark = current_user.favorites.find(params[:id]).landmark
      current_user.unfavorite(landmark)
      redirect_back fallback_location: people_path
    end
  end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def show
    @person = Person.find(params[:id])
    gon.landmarks = @person.landmarks
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to people_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    logout
    redirect_to people_path, success: 'ログアウトしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
      end
    
      def create
        @user = User.new(user_params)
        if @user.save
          redirect_to people_path, success: 'ユーザー登録に成功しました'
        else
          flash.now[:danger] = "ユーザー登録に失敗しました"
          render :new
        end
      end
    
      private
    
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end
end

app/helpers/admin/people_helper.rb
module Admin::PeopleHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HistoryRelationMap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= Gon::Base.render_data %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if logged_in? %>
    <%= render 'admin/shared/header' %>
  <% end %>
  <%= render 'shared/flash_message' %>
  <%= yield %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-secondary mb-3">
    <div class="container">
      <%= link_to "平安末期〜鎌倉時代の人物マップ", root_path, class: 'navbar-brand'%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item d-flex">
            <%= link_to "新規登録", new_user_path, class: "nav-link active ms-2 mt-1" %>
            <%= link_to "人物ソート", people_path, class: "nav-link active ms-2 mt-1" %>
            <%= link_to "ログイン", login_path, class: "nav-link active ms-2 mt-1" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="fixed-bottom bg-secondary text-white" >
    <div class="container">
      <div class="row">
        <div class="col-sm-4 col-5">
          <p>Copyright © 2022 平安末期〜鎌倉時代の人物マップ</p>
        </div>
        <div  class="col-sm-2 col">
          <%= link_to '利用規約', terms_path, style: "color: white" %>
        </div>
        <div  class="col-sm-2 col">
          <%= link_to 'プライバシーポリシー', privacy_path, style: "color: white" %>
        </div>
        <div  class="col-sm-2 col">
          <%= link_to '開発者Twitter', 'https://twitter.com/heian_kama_map', style: "color: white" %>
        </div>
      </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-secondary mb-3">
    <div class="container">
      <%= link_to "平安末期〜鎌倉時代の人物マップ", root_path, class: 'navbar-brand'%>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item d-flex">
            <%= link_to "人物ソート", people_path, class: "nav-link active ms-2 mt-1" %>
            <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link active ms-2 mt-1" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>