config/routes.rb
Rails.application.routes.draw do
  root 'people#index'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  resources :maps, only: %i[show]
  resources :people, only: %i[index show]
  resources :users, only: %i[new create]
  get 'static_pages/top'
  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy'
  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users
    resources :people
    resources :landmarks
  end
  resources :favorites, only: %i[create destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :landmark

  validates :user_id, uniqueness: { scope: :landmark_id }
end

app/models/landmark.rb
class Landmark < ApplicationRecord
  validates :name, presence: true
  belongs_to :person
  
  has_many :favorites
end

app/models/person.rb
class Person < ApplicationRecord
    validates :name, presence: true
    has_many :landmarks, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true, presence: true
  validates :name, presence: true, length: { maximum: 225 }
  enum role: { general: 0, admin: 1 }

  has_many :favorites, dependent: :destroy
  has_many :landmarks, through: :favorites

  def favorite(landmark)
    landmarks << landmark
  end

  def unfavorite(landmark)
    landmarks.destroy(landmark)
  end

  def favorite?(landmark)
    landmarks.include?(landmark)
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
    before_action :require_login
    before_action :check_admin
    layout 'admin/layouts/application'

    private

    def not_authenticated
        redirect_to admin_login_path
    end

    def check_admin
        redirect_to admin_login_path unless current_user.admin?
    end
end

app/controllers/admin/landmarks_controller.rb
class Admin::LandmarksController < Admin::BaseController
    before_action :set_landmark, only: %i[edit update show destroy]

    def new
      @landmark = Landmark.new
    end

    def index
        @q = Landmark.ransack(params[:q])
        @landmarks = @q.result(distinct: true)
    end

    def edit; end

    def create
      @landmark = Landmark.new(landmark_params)
        if @landmark.save
          redirect_to admin_landmarks_path, success: '施設を登録しました'
        else
          flash.now[:danger] = "施設の登録に失敗しました"
          render :new
        end
    end

    def update
        if @landmark.update(landmark_params)
          redirect_to admin_landmarks_path, success: '編集しました'
        else
          flash.now[:danger] = "編集に失敗しました"
          render :edit
        end
    end

    def show; end

    def destroy
        @landmark.destroy!
        redirect_to admin_landmarks_path, success: '削除しました'
    end

    private

    def set_landmark
        @landmark = Landmark.find(params[:id])
    end

    def landmark_params
        params.require(:landmark).permit(:person_id, :name, :description_with_person, :longitude, :latitude, :address)
    end
end

app/controllers/admin/people_controller.rb
class Admin::PeopleController < Admin::BaseController
before_action :set_person, only: %i[edit update show destroy]

  def new
    @person = Person.new
  end

  def index
    @q = Person.ransack(params[:q])
    @people = @q.result(distinct: true)
  end

  def edit; end

  def create
      @person = Person.new(person_params)
      if @person.save
        redirect_to admin_people_path, success: '人物データの登録に成功しました'
      else
        flash.now[:danger] = '人物データの登録に失敗しました'
        render :new
      end
  end

  def update
    if @person.update(person_params)
      redirect_to admin_person_path, success: '編集に成功しました'
    else
      flash.now[:danger] = '編集に失敗しました'
      render :edit
    end
  end

  def show; end

  def destroy
    @person.destroy!
    redirect_to admin_people_path, success: '削除しました'
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:name, :description)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
    before_action :set_user, only: %i[edit update show destroy]
    def index
        @q = User.ransack(params[:q])
        @users = @q.result(distinct: true)
    end

    def edit; end

    def update
        if @user.update(user_params)
          redirect_to admin_users_path,  success: '編集に成功しました'
        else
          flash.now[:danger] = "編集に失敗しました"
          render :edit
        end
    end

    def show; end

    def destroy
        @user.destroy!
        redirect_to admin_users_path, success: '削除しました'
      end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:name, :email, :role)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :success, :danger
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
      landmark = Landmark.find(params[:landmark_id])
      current_user.favorite(landmark)
      redirect_back fallback_location: people_path
    end
  
    def destroy
      landmark = current_user.favorites.find(params[:id]).landmark
      current_user.unfavorite(landmark)
      redirect_back fallback_location: people_path
    end
  end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def show
    @person = Person.find(params[:id])
    gon.landmarks = @person.landmarks
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to people_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    logout
    redirect_to people_path, success: 'ログアウトしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
      end
    
      def create
        @user = User.new(user_params)
        if @user.save
          redirect_to people_path, success: 'ユーザー登録に成功しました'
        else
          flash.now[:danger] = "ユーザー登録に失敗しました"
          render :new
        end
      end
    
      private
    
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end
end

app/helpers/admin/landmarks_helper.rb
module Admin::LandmarksHelper
end

app/helpers/admin/people_helper.rb
module Admin::PeopleHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/people/_person.html.erb
<tr>
  <td>
    <%= person.id %>
  </td>
  <td>
    <%= person.name %>
  </td>
  <td>
    <%= person.description %>
  </td>
  <td>
    <%= link_to '詳細', admin_person_path(person), class: 'btn btn-info' %>
    <%= link_to '編集', edit_admin_person_path(person), class: 'btn btn-success' %>
    <%= link_to '削除', admin_person_path(person), method: :delete, data: { confirm: "削除しますか?" }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/people/edit.html.erb
<div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <%= form_with model: @person, url: admin_person_path(@person), local: true do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_field :description, class: 'form-control' %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
   </div>
</div>

app/views/admin/people/index.html.erb
<div>
  <div class="row">
    <div class="col-md-12 mb-3">
      <%= search_form_for @q, url: admin_people_path do |f| %>
        <%= f.label :name_cont, '人物名' %>
        <%= f.search_field :name_cont %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">名前</th>
          <th scope="col">説明</th>
        </tr>
        </thead>
        <tbody>
          <%= render @people %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/people/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1>人物登録</h1>
      <%= form_with model: @person, url: {action: 'create'}, local: true do |f| %>
        <div class="mb-3">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="mb-3">
          <%= f.label :description %>
          <%= f.text_field :description, class: 'form-control' %>
        <%= f.submit '登録', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/people/show.html.erb
<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
    <div class="text-right mb-3">
      <%= link_to "編集", edit_admin_person_path(@person), class: 'btn btn-success' %>
      <%= link_to "削除", admin_person_path(@person), method: :delete, data: { confirm: "削除しますか?" }, class: 'btn btn-danger' %>
    </div>
    <table class="table table-bordered bg-white">
      <tr>
        <th scope="row"><%= "id" %></th>
        <td><%= @person.id %></td>
      </tr>
      <tr>
        <th scope="row"><%= "名前" %></th>
        <td><%= @person.name %></td>
      </tr>
      <tr>
        <th scope="row"><%= "詳細" %></th>
        <td><%= @person.description %></td>
      </tr>
    </table>
  </div>
</div>

app/views/admin/users/_user.html.erb
<tr>
  <td>
    <%= user.name %>
  </td>
  <td>
    <%= user.email %>
  </td>
  <td>
    <%= user.role %>
  </td>
  <td>
    <%= link_to '詳細', admin_user_path(user), class: 'btn btn-info' %>
    <%= link_to '編集', edit_admin_user_path(user), class: 'btn btn-success' %>
    <%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: "削除しますか?" }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/users/edit.html.erb
<div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <%= form_with model: @user, url: admin_user_path(@user), local: true do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :role %>
          <%= f.select :role, User.roles.keys.to_a, {}, class: 'form-control' %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

app/views/admin/users/index.html.erb
<div>
  <div class="row">
    <div class="col-md-12 mb-3">
      <%= search_form_for @q, url: admin_users_path do |f| %>
        <%= f.label :name_cont, 'ユーザー名' %>
        <%= f.search_field :name_cont %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col">名前</th>
          <th scope="col">メールアドレス</th>
          <th scope="col">権限</th>
        </tr>
        </thead>
        <tbody>
          <%= render @users %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="row">
  <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
    <div class="text-right mb-3">
      <%= link_to "編集", edit_admin_user_path(@user), class: 'btn btn-success' %>
      <%= link_to "削除", admin_user_path(@user), method: :delete, data: { confirm: "削除しますか?" }, class: 'btn btn-danger' %>
    </div>
    <table class="table table-bordered bg-white">
      <tr>
        <th scope="row"><%= "名前" %></th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th scope="row"><%= "メールアドレス" %></th>
        <td><%= @user.email%></td>
      </tr>
      <tr>
        <th scope="row"><%= "権限" %></th>
        <td><%= @user.role %></td>
      </tr>
    </table>
  </div>
</div>

app/views/people/_favorite.html.erb
<%= link_to favorites_path(landmark_id: landmark.id),  class:"float-right", method: :post do %>
    <i class="fa-regular fa-star"></i>
<% end %>

app/views/people/_favorite_button.html.erb
<% if current_user.favorite?(landmark) %>
  <%= render 'people/unfavorite', { landmark: landmark } %>
<% else %>
  <%= render 'people/favorite', { landmark: landmark } %>
<% end %>

app/views/people/_landmark.html.erb
<h5 class="text-center"><%= link_to @person.name, person_path(@person) %>の関連施設</h5> 
<% @person.landmarks.each do |landmark| %>
  <div class="card text-center rounded-pill mb-3">
    <div class="card-body row">
      <div class="col-3 d-flex align-items-center" >
        <%= landmark.name %>
      </div>
      <div class="col-6">
        <%= landmark.description_with_person %>
      </div>
      <% if logged_in? %>
        <div class="col-1 d-flex align-items-center justify-content-end">
          <%= render 'people/favorite_button', landmark: landmark %>
        </div>
      <% end %>
      <div class="col-2 d-flex align-items-center">
        <%= "#{landmark.favorites.length}件のお気に入り" %>
      </div>
    </div>
  </div>
<% end %>

app/views/people/_unfavorite.html.erb
<%= link_to favorite_path(current_user.favorites.find_by(landmark_id: landmark.id)), class:"float-right", method: :delete do %>
    <i class="fa-solid fa-star"></i>
<% end %>

app/views/people/index.html.erb
<div class="list-group w-75 mx-auto">
  <% @people.each do |person| %>
    <div class="list-group-item list-group-item-action"><%= link_to person.name, map_path(person), 'data-turbolinks': false %></div>
  <% end %>
</div>

app/views/people/show.html.erb
<div class="container-lg">
  <div class='row' >
    <div class="card w-50 border-dark col h-100">
      <div class="card-body">
        <h4 class="card-title text-center"><%= @person.name %>についての説明</h4>
        <p class="card-text"><%= @person.description %></p>
        <%= link_to '地図を表示', map_path(@person), 'data-turbolinks': false %>
      </div>
    </div>
    <div class="row mb-5 mt-3">
      <%= render "landmark" %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1>ユーザー登録</h1>
      <%= form_with model: @user, local: true do |f| %>
        <div class="mb-3">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="mb-3">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        <div class="mb-3">
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit '登録', class: 'btn btn-primary' %>
      <% end %>
      <div class='text-center'>
        <%= link_to 'ログインページへ', login_path %>
      </div>
    </div>
  </div>
</div>